# BEFORE ANYTHING ELSE: UPDATE YOUR ABSOLUTE PROJECT PATH
root_dir: E:/UML-25/

dataset_name: fly
# dataset_name: fly_toy

dataset_config: ${root_dir}/configs/config_${dataset_name}.yaml

dataset_dir: ${root_dir}/data/${dataset_name}

outputs_dir: ${root_dir}/outputs/${dataset_name}

train:
  model_type: MLP  # or GNN
  seed: 42
  max_epochs: 100
  val_ratio: 0.2

  use_confidence: True
  run_grid_search: True
  run_eval_on_ood: True
  force_grid: True

