# BEFORE ANYTHING ELSE: UPDATE YOUR ABSOLUTE PROJECT PATH
root_dir: E:/UML-25/

dataset_name: fly
# dataset_name: fly_toy

dataset_config: ${root_dir}/configs/config_${dataset_name}.yaml

dataset_dir: ${root_dir}/data/${dataset_name}

outputs_dir: ${root_dir}/outputs/${dataset_name}

train:
  model_type: MLP  # or GNN
  mode: loo  # or loo
  seed: 0  # let's always use 42 for refine testing, 0 for loo testing
  max_epochs: 100
  val_ratio: 0.2

  use_confidence: True
  run_grid_search: True
  force_grid: False  # True: Will always do grid search even if there's a best_result.json
  run_eval_on_ood: True
